# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bb9c3cd1eb111fc2c6667cb0486930acfc9aea94eb405e90c7c9b7a0112cd62c2c4dfc85aa124895d03a981c54d64428eb61dff81dd5ce109636342bd3d6ec8

test:
  secret_key_base: 2195cfdc6994a09908b88694617178f94b04da5bd2278812a787112a9456ed6c25661a52df50960c5811cc9b5aed70b85d363b87f84f6cb7a02525a52247cc6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c921b0314d6b758386d31286b58a05cd583850e0de0530e3d8ab5915783fbb189b03d8cbd0142e8db93efd08b6c01c661d90072747c8561f6ac16f6b61332e7f
